server:
  port: "8000"

mysql:
  dsn: "root:root@tcp(localhost:3306)/clouddisk_db?charset=utf8mb4&parseTime=True&loc=Local"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

minio:
  endpoint: "localhost:9000"
  access_key_id: "minioadmin"
  secret_access_key: "minioadmin"
  use_ssl: false
  bucket_name: "go-clouddisk-bucket"

aliyun_oss:
  endpoint: "oss-cn-hangzhou.aliyuncs.com(替换为你的实际 Endpoint)"
  access_key_id: "YOUR_ALIYUN_ACCESS_KEY_ID"
  secret_access_key: "YOUR_ALIYUN_SECRET_ACCESS_KEY"
  bucket_name: "your-aliyun-oss-bucket"
  use_ssl: true

rabbitmq:
  url: "amqp://guest:guest@rabbitmq:5672/"

jwt:
  secret_key: "MTg5ODg2OTE1MjAyNS8zLzEyIDE4OjU0OjU3"
  expires_in: 60
  refresh_expire_hours: 168 # 7 days
  issuer: "go-clouddisk"

storageconfig:
  local_base_path: "./uploads/data"
  type: "minio"

log:
  output_path: "logs/app.log"
  error_path: "logs/error.log"
  level: "info" # debug, info, warn, error, dpanic, panic, fatal

elasticsearch:
  addresses: ["http://localhost:9200"] # 使用 Docker Compose 服务名和内部端口
  username: "" # 如果 Elasticsearch 启用安全认证，需要填写
  password: "" # 如果 Elasticsearch 启用安全认证，需要填写
  # cloud_id: ""                           # 如果使用 Elastic Cloud，需要填写
  # api_key: ""                            # 如果使用 API Key 认证
