# filebeat.yml
filebeat.inputs:
  - type: filestream
    id: go-app-logs
    enabled: true
    paths:
      - /usr/share/filebeat/logs/app.log # 这是在 Filebeat 容器内部的路径
      - /usr/share/filebeat/logs/error.log # 这是在 Filebeat 容器内部的路径
    json.keys_under_root: true
    json.overwrite_keys: true
    json.add_error_key: true

filebeat.modules:
  - module: system
    syslog:
      enabled: true
    auth:
      enabled: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"] # 指向 Docker Compose 网络中的 Elasticsearch 服务名
  # username: "elastic" # 如果您的 Elasticsearch 启用了安全认证
  # password: "your_elastic_password"

setup.kibana:
  host: "kibana:5601" # 指向 Docker Compose 网络中的 Kibana 服务名
